### ISSUE TITLE
[META] Modernize ELT -- Browser Compatibility / Ember CLI 2.13

### ISSUE THREAD

**Issue by alexander-alvarez** [offirgolan/ember-light-table#430]
This issue has been opened for a while https://github.com/offirgolan/ember-light-table/issues/145 and hasn't been addressed.

Since the time that it has been open things have been added to the ecosystem to make the ergonomics of compatibility support better. Specifically [targets](https://www.emberjs.com/blog/2017/04/29/ember-2-13-released.html#toc_targets).

Issues such as https://github.com/offirgolan/ember-light-table/issues/427 and https://github.com/offirgolan/ember-light-table/issues/343 will go away automagically because of the functionality in [babel-preset-env](https://github.com/babel/babel-preset-env/blob/master/data/built-in-features.js#L143). Similarly we'll be more aligned with the community best practices.

### :skull_and_crossbones:  `bower.json`
- [ ] Update `ember-cli` to 2.13, reconfigure to use npm & `ember-source` instead of bower
- [ ] `Faker` / `Pretender` shouldn't be needed in bower.json as those are brought in by `ember-cli-mirage` https://github.com/offirgolan/ember-light-table/blob/master/bower.json
- [ ] `Font-awesome` should be a `devDependency` when we move it to the `package.json` -- from what I could see in this [search](https://github.com/offirgolan/ember-light-table/search?p=1&q=fa&type=&utf8=%E2%9C%93). It's css should be brought in for the demo app by using `ember-cli-build.js`. We should document this, so it's no surprise that the ascending and descending icons don't work if users drag and drop our code snippets, don't have font-awesome, and haven't copied our setup.
- [ ] Kill bower.json

### Compatibility Related
- [ ] Document what features we use that we know aren't the most browser compatible including (https://github.com/offirgolan/ember-light-table/issues/427, https://github.com/offirgolan/ember-light-table/issues/343, and https://github.com/offirgolan/ember-light-table/pull/426) and push them to use targets to replace them

### Other
- [ ] Upgrade from jshint to eslint (enabled once we upgrade ember-cli)

--- 

As always, any and all help is welcome. Feel free to chime in the comments to pick up a task, and I'll add your name alongside the task

---
Reference
http://rwjblue.com/2017/04/21/ember-cli-targets/
[ember-source](https://www.emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_ember-no-longer-supplied-via-code-bower-code)

Eslint
https://www.emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_eslint-all-the-things
https://github.com/ember-cli/ember-new-output/blob/master/.eslintrc.js

**Comment by buschtoens** [comment]
I have a passion for killing `bower.json` files. :stuck_out_tongue_winking_eye:  
I'd love to take over these four tasks. :)
