### ISSUE TITLE
[Tracking] Remove jQuery 

### ISSUE THREAD

**Issue by donaldwasserman** [offirgolan/ember-light-table#594]
@alexander-alvarez Just to move this this issue to track where we’re at. 

Right now: 

- [x] Upgrade tests/configuration Here
- [x] Update Ember Scrollable [PR](https://github.com/alphasights/ember-scrollable/pull/98)
	- [x] Update Ember-Resize Detector [PR](https://github.com/EmberSherpa/ember-element-resize-detector/pull/17)

**Comment by fran-worley** [comment]
@donaldwasserman looks like https://github.com/EmberSherpa/ember-element-resize-detector/pull/17 was merged - one down... 2 to go!

**Comment by fran-worley** [comment]
I'm going to escalate this to BUG now as from ember 3.9 the use of `this.$()` was [deprecated](https://deprecations.emberjs.com/v3.x#toc_jquery-apis).

The use of jQuery directly in ELT has been removed but it remains in ember scrollable pending completion of https://github.com/alphasights/ember-scrollable/pull/98

**Comment by donaldwasserman** [comment]
Hey @fran-worley - I made some progress on ember-scrollable last week, but there are some failing tests I couldn’t figure out and I’m traveling this week. Feedback welcome on that if you have any ideas!

**Comment by donaldwasserman** [comment]
Hi @fran-worley see https://github.com/alphasights/ember-scrollable/pull/98 tests should be passing soon.

**Comment by fran-worley** [comment]
This was addressed in 2.0.0-beta.5 so marking as resolved
